// This file is generated by rust-protobuf 2.0.6. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct TopicConfig {
    // message fields
    pub message_size_limit: u64,
    pub segment_size_limit: u64,
    pub index_after_bytes: u64,
    pub rotate_segment_after_seconds: u64,
    pub stale_segment_seconds: u64,
    pub log_maintenance_period: u64,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl TopicConfig {
    pub fn new() -> TopicConfig {
        ::std::default::Default::default()
    }

    // uint64 message_size_limit = 1;

    pub fn clear_message_size_limit(&mut self) {
        self.message_size_limit = 0;
    }

    // Param is passed by value, moved
    pub fn set_message_size_limit(&mut self, v: u64) {
        self.message_size_limit = v;
    }

    pub fn get_message_size_limit(&self) -> u64 {
        self.message_size_limit
    }

    // uint64 segment_size_limit = 2;

    pub fn clear_segment_size_limit(&mut self) {
        self.segment_size_limit = 0;
    }

    // Param is passed by value, moved
    pub fn set_segment_size_limit(&mut self, v: u64) {
        self.segment_size_limit = v;
    }

    pub fn get_segment_size_limit(&self) -> u64 {
        self.segment_size_limit
    }

    // uint64 index_after_bytes = 3;

    pub fn clear_index_after_bytes(&mut self) {
        self.index_after_bytes = 0;
    }

    // Param is passed by value, moved
    pub fn set_index_after_bytes(&mut self, v: u64) {
        self.index_after_bytes = v;
    }

    pub fn get_index_after_bytes(&self) -> u64 {
        self.index_after_bytes
    }

    // uint64 rotate_segment_after_seconds = 4;

    pub fn clear_rotate_segment_after_seconds(&mut self) {
        self.rotate_segment_after_seconds = 0;
    }

    // Param is passed by value, moved
    pub fn set_rotate_segment_after_seconds(&mut self, v: u64) {
        self.rotate_segment_after_seconds = v;
    }

    pub fn get_rotate_segment_after_seconds(&self) -> u64 {
        self.rotate_segment_after_seconds
    }

    // uint64 stale_segment_seconds = 5;

    pub fn clear_stale_segment_seconds(&mut self) {
        self.stale_segment_seconds = 0;
    }

    // Param is passed by value, moved
    pub fn set_stale_segment_seconds(&mut self, v: u64) {
        self.stale_segment_seconds = v;
    }

    pub fn get_stale_segment_seconds(&self) -> u64 {
        self.stale_segment_seconds
    }

    // uint64 log_maintenance_period = 6;

    pub fn clear_log_maintenance_period(&mut self) {
        self.log_maintenance_period = 0;
    }

    // Param is passed by value, moved
    pub fn set_log_maintenance_period(&mut self, v: u64) {
        self.log_maintenance_period = v;
    }

    pub fn get_log_maintenance_period(&self) -> u64 {
        self.log_maintenance_period
    }
}

impl ::protobuf::Message for TopicConfig {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.message_size_limit = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.segment_size_limit = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.index_after_bytes = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.rotate_segment_after_seconds = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.stale_segment_seconds = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.log_maintenance_period = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.message_size_limit != 0 {
            my_size += ::protobuf::rt::value_size(1, self.message_size_limit, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.segment_size_limit != 0 {
            my_size += ::protobuf::rt::value_size(2, self.segment_size_limit, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.index_after_bytes != 0 {
            my_size += ::protobuf::rt::value_size(3, self.index_after_bytes, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.rotate_segment_after_seconds != 0 {
            my_size += ::protobuf::rt::value_size(4, self.rotate_segment_after_seconds, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.stale_segment_seconds != 0 {
            my_size += ::protobuf::rt::value_size(5, self.stale_segment_seconds, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.log_maintenance_period != 0 {
            my_size += ::protobuf::rt::value_size(6, self.log_maintenance_period, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.message_size_limit != 0 {
            os.write_uint64(1, self.message_size_limit)?;
        }
        if self.segment_size_limit != 0 {
            os.write_uint64(2, self.segment_size_limit)?;
        }
        if self.index_after_bytes != 0 {
            os.write_uint64(3, self.index_after_bytes)?;
        }
        if self.rotate_segment_after_seconds != 0 {
            os.write_uint64(4, self.rotate_segment_after_seconds)?;
        }
        if self.stale_segment_seconds != 0 {
            os.write_uint64(5, self.stale_segment_seconds)?;
        }
        if self.log_maintenance_period != 0 {
            os.write_uint64(6, self.log_maintenance_period)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TopicConfig {
        TopicConfig::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "message_size_limit",
                    |m: &TopicConfig| { &m.message_size_limit },
                    |m: &mut TopicConfig| { &mut m.message_size_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "segment_size_limit",
                    |m: &TopicConfig| { &m.segment_size_limit },
                    |m: &mut TopicConfig| { &mut m.segment_size_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "index_after_bytes",
                    |m: &TopicConfig| { &m.index_after_bytes },
                    |m: &mut TopicConfig| { &mut m.index_after_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "rotate_segment_after_seconds",
                    |m: &TopicConfig| { &m.rotate_segment_after_seconds },
                    |m: &mut TopicConfig| { &mut m.rotate_segment_after_seconds },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "stale_segment_seconds",
                    |m: &TopicConfig| { &m.stale_segment_seconds },
                    |m: &mut TopicConfig| { &mut m.stale_segment_seconds },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "log_maintenance_period",
                    |m: &TopicConfig| { &m.log_maintenance_period },
                    |m: &mut TopicConfig| { &mut m.log_maintenance_period },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<TopicConfig>(
                    "TopicConfig",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static TopicConfig {
        static mut instance: ::protobuf::lazy::Lazy<TopicConfig> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const TopicConfig,
        };
        unsafe {
            instance.get(TopicConfig::new)
        }
    }
}

impl ::protobuf::Clear for TopicConfig {
    fn clear(&mut self) {
        self.clear_message_size_limit();
        self.clear_segment_size_limit();
        self.clear_index_after_bytes();
        self.clear_rotate_segment_after_seconds();
        self.clear_stale_segment_seconds();
        self.clear_log_maintenance_period();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TopicConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TopicConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cconfig.proto\x12\x05slogd\"\xc0\x02\n\x0bTopicConfig\x12,\n\x12mes\
    sage_size_limit\x18\x01\x20\x01(\x04R\x10messageSizeLimit\x12,\n\x12segm\
    ent_size_limit\x18\x02\x20\x01(\x04R\x10segmentSizeLimit\x12*\n\x11index\
    _after_bytes\x18\x03\x20\x01(\x04R\x0findexAfterBytes\x12?\n\x1crotate_s\
    egment_after_seconds\x18\x04\x20\x01(\x04R\x19rotateSegmentAfterSeconds\
    \x122\n\x15stale_segment_seconds\x18\x05\x20\x01(\x04R\x13staleSegmentSe\
    conds\x124\n\x16log_maintenance_period\x18\x06\x20\x01(\x04R\x14logMaint\
    enancePeriodB\x18\n\nslog.protoP\x01\xa0\x01\x01Z\x05protob\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
